{% import _self as errors %}

{% macro exception(exception) %}
    {% import _self as errors %}
    <h3>Previous exception:</h3>
    <dl>
        <dt>File:</dt>
        <dd>
            <pre class="prettyrpint linenums">{{ exception.getFile() }}: {{ exception.getLine() }}</pre>
        </dd>
        <dt>Message:</dt>
        <dd>
            <pre class="prettyprint linenums">{{ exception.getMessage() }}</pre>
        </dd>
        <dt>Stack trace:</dt>
        <dl>
            <pre class="prettyprint linenums">{{ exception.getTraceAsString() }}</pre>
        </dl>
    </dl>
    {% if exception.previous %}
        {{ errors.exception(exception.previous) }}
    {% endif %}
{% endmacro %}

<h1>An error occurred</h1>
<h2>{{ message }}</h2>

{% if display_exceptions %}
    {% if exception %}
        <hr/>
        <h2>Additional information:</h2>
        <dl>
            <dt>File:</dt>
            <dd>
                <pre class="prettyrpint linenums">{{ exception.getFile() }}: {{ exception.getLine() }}</pre>
            </dd>
            <dt>Message:</dt>
            <dd>
                <pre class="prettyprint linenums">{{ exception.getMessage() }}</pre>
            </dd>
            <dt>Stack trace:</dt>
            <dl>
                <pre class="prettyprint linenums">{{ exception.getTraceAsString() }}</pre>
            </dl>
        </dl>
        {% if exception.previous %}
            {{ errors.exception(exception.previous) }}
        {% endif %}
    {% endif %}
{% endif %}
